#pragma once

// PlayerUnknown's Battle Ground Mobile (1.6.0) SDK

#include "PUBGM_Basic.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Enums
//---------------------------------------------------------------------------

// UserDefinedEnum BP_UIENUM_UIElemTypes.BP_UIENUM_UIElemTypes
enum class EBP_UIENUM_UIElemTypes : uint8_t
{
	BP_UIENUM_UIElemTypes__NewEnumerator0 = 0,
	BP_UIENUM_UIElemTypes__NewEnumerator1 = 1,
	BP_UIENUM_UIElemTypes__NewEnumerator2 = 2,
	BP_UIENUM_UIElemTypes__NewEnumerator3 = 3,
	BP_UIENUM_UIElemTypes__NewEnumerator4 = 4,
	BP_UIENUM_UIElemTypes__NewEnumerator21 = 5,
	BP_UIENUM_UIElemTypes__NewEnumerator6 = 6,
	BP_UIENUM_UIElemTypes__NewEnumerator7 = 7,
	BP_UIENUM_UIElemTypes__NewEnumerator5 = 8,
	BP_UIENUM_UIElemTypes__NewEnumerator9 = 9,
	BP_UIENUM_UIElemTypes__NewEnumerator10 = 10,
	BP_UIENUM_UIElemTypes__NewEnumerator11 = 11,
	BP_UIENUM_UIElemTypes__NewEnumerator12 = 12,
	BP_UIENUM_UIElemTypes__NewEnumerator13 = 13,
	BP_UIENUM_UIElemTypes__NewEnumerator14 = 14,
	BP_UIENUM_UIElemTypes__NewEnumerator15 = 15,
	BP_UIENUM_UIElemTypes__NewEnumerator16 = 16,
	BP_UIENUM_UIElemTypes__NewEnumerator17 = 17,
	BP_UIENUM_UIElemTypes__NewEnumerator18 = 18,
	BP_UIENUM_UIElemTypes__NewEnumerator19 = 19,
	BP_UIENUM_UIElemTypes__NewEnumerator23 = 20,
	BP_UIENUM_UIElemTypes__NewEnumerator24 = 21,
	BP_UIENUM_UIElemTypes__NewEnumerator25 = 22,
	BP_UIENUM_UIElemTypes__NewEnumerator26 = 23,
	BP_UIENUM_UIElemTypes__NewEnumerator27 = 24,
	BP_UIENUM_UIElemTypes__NewEnumerator28 = 25,
	BP_UIENUM_UIElemTypes__NewEnumerator29 = 26,
	BP_UIENUM_UIElemTypes__NewEnumerator30 = 27,
	BP_UIENUM_UIElemTypes__NewEnumerator32 = 28,
	BP_UIENUM_UIElemTypes__NewEnumerator33 = 29,
	BP_UIENUM_UIElemTypes__NewEnumerator34 = 30,
	BP_UIENUM_UIElemTypes__NewEnumerator35 = 31,
	BP_UIENUM_UIElemTypes__NewEnumerator36 = 32,
	BP_UIENUM_UIElemTypes__NewEnumerator37 = 33,
	BP_UIENUM_UIElemTypes__NewEnumerator38 = 34,
	BP_UIENUM_UIElemTypes__NewEnumerator39 = 35,
	BP_UIENUM_UIElemTypes__NewEnumerator40 = 36,
	BP_UIENUM_UIElemTypes__NewEnumerator41 = 37,
	BP_UIENUM_UIElemTypes__NewEnumerator42 = 38,
	BP_UIENUM_UIElemTypes__NewEnumerator43 = 39,
	BP_UIENUM_UIElemTypes__NewEnumerator44 = 40,
	BP_UIENUM_UIElemTypes__NewEnumerator45 = 41,
	BP_UIENUM_UIElemTypes__NewEnumerator46 = 42,
	BP_UIENUM_UIElemTypes__NewEnumerator47 = 43,
	BP_UIENUM_UIElemTypes__NewEnumerator48 = 44,
	BP_UIENUM_UIElemTypes__NewEnumerator49 = 45,
	BP_UIENUM_UIElemTypes__NewEnumerator50 = 46,
	BP_UIENUM_UIElemTypes__NewEnumerator51 = 47,
	BP_UIENUM_UIElemTypes__NewEnumerator52 = 48,
	BP_UIENUM_UIElemTypes__NewEnumerator53 = 49,
	BP_UIENUM_UIElemTypes__NewEnumerator54 = 50,
	BP_UIENUM_UIElemTypes__NewEnumerator55 = 51,
	BP_UIENUM_UIElemTypes__NewEnumerator56 = 52,
	BP_UIENUM_UIElemTypes__NewEnumerator57 = 53,
	BP_UIENUM_UIElemTypes__NewEnumerator58 = 54,
	BP_UIENUM_UIElemTypes__NewEnumerator59 = 55,
	BP_UIENUM_UIElemTypes__NewEnumerator60 = 56,
	BP_UIENUM_UIElemTypes__NewEnumerator61 = 57,
	BP_UIENUM_UIElemTypes__NewEnumerator62 = 58,
	BP_UIENUM_UIElemTypes__NewEnumerator63 = 59,
	BP_UIENUM_UIElemTypes__NewEnumerator64 = 60,
	BP_UIENUM_UIElemTypes__NewEnumerator65 = 61,
	BP_UIENUM_UIElemTypes__NewEnumerator66 = 62,
	BP_UIENUM_UIElemTypes__NewEnumerator67 = 63,
	BP_UIENUM_UIElemTypes__NewEnumerator68 = 64,
	BP_UIENUM_UIElemTypes__NewEnumerator69 = 65,
	BP_UIENUM_UIElemTypes__NewEnumerator70 = 66,
	BP_UIENUM_UIElemTypes__NewEnumerator71 = 67,
	BP_UIENUM_UIElemTypes__NewEnumerator72 = 68,
	BP_UIENUM_UIElemTypes__NewEnumerator73 = 69,
	BP_UIENUM_UIElemTypes__NewEnumerator74 = 70,
	BP_UIENUM_UIElemTypes__NewEnumerator75 = 71,
	BP_UIENUM_UIElemTypes__NewEnumerator76 = 72,
	BP_UIENUM_UIElemTypes__NewEnumerator77 = 73,
	BP_UIENUM_UIElemTypes__NewEnumerator78 = 74,
	BP_UIENUM_UIElemTypes__NewEnumerator79 = 75,
	BP_UIENUM_UIElemTypes__NewEnumerator80 = 76,
	BP_UIENUM_UIElemTypes__NewEnumerator81 = 77,
	BP_UIENUM_UIElemTypes__NewEnumerator82 = 78,
	BP_UIENUM_UIElemTypes__NewEnumerator83 = 79,
	BP_UIENUM_UIElemTypes__NewEnumerator84 = 80,
	BP_UIENUM_UIElemTypes__NewEnumerator85 = 81,
	BP_UIENUM_UIElemTypes__NewEnumerator86 = 82,
	BP_UIENUM_UIElemTypes__NewEnumerator87 = 83,
	BP_UIENUM_UIElemTypes__NewEnumerator88 = 84,
	BP_UIENUM_UIElemTypes__NewEnumerator89 = 85,
	BP_UIENUM_UIElemTypes__NewEnumerator90 = 86,
	BP_UIENUM_UIElemTypes__NewEnumerator91 = 87,
	BP_UIENUM_UIElemTypes__NewEnumerator92 = 88,
	BP_UIENUM_UIElemTypes__NewEnumerator94 = 89,
	BP_UIENUM_UIElemTypes__NewEnumerator95 = 90,
	BP_UIENUM_UIElemTypes__NewEnumerator96 = 91,
	BP_UIENUM_UIElemTypes__NewEnumerator97 = 92,
	BP_UIENUM_UIElemTypes__NewEnumerator98 = 93,
	BP_UIENUM_UIElemTypes__NewEnumerator99 = 94,
	BP_UIENUM_UIElemTypes__NewEnumerator100 = 95,
	BP_UIENUM_UIElemTypes__NewEnumerator101 = 96,
	BP_UIENUM_UIElemTypes__NewEnumerator102 = 97,
	BP_UIENUM_UIElemTypes__NewEnumerator103 = 98,
	BP_UIENUM_UIElemTypes__NewEnumerator104 = 99,
	BP_UIENUM_UIElemTypes__NewEnumerator105 = 100,
	BP_UIENUM_UIElemTypes__NewEnumerator106 = 101,
	BP_UIENUM_UIElemTypes__NewEnumerator107 = 102,
	BP_UIENUM_UIElemTypes__NewEnumerator108 = 103,
	BP_UIENUM_UIElemTypes__NewEnumerator109 = 104,
	BP_UIENUM_UIElemTypes__NewEnumerator110 = 105,
	BP_UIENUM_UIElemTypes__NewEnumerator111 = 106,
	BP_UIENUM_UIElemTypes__NewEnumerator112 = 107,
	BP_UIENUM_UIElemTypes__NewEnumerator113 = 108,
	BP_UIENUM_UIElemTypes__NewEnumerator114 = 109,
	BP_UIENUM_UIElemTypes__NewEnumerator115 = 110,
	BP_UIENUM_UIElemTypes__NewEnumerator116 = 111,
	BP_UIENUM_UIElemTypes__NewEnumerator117 = 112,
	BP_UIENUM_UIElemTypes__NewEnumerator118 = 113,
	BP_UIENUM_UIElemTypes__NewEnumerator119 = 114,
	BP_UIENUM_UIElemTypes__NewEnumerator120 = 115,
	BP_UIENUM_UIElemTypes__NewEnumerator121 = 116,
	BP_UIENUM_UIElemTypes__NewEnumerator122 = 117,
	BP_UIENUM_UIElemTypes__NewEnumerator123 = 118,
	BP_UIENUM_UIElemTypes__NewEnumerator124 = 119,
	BP_UIENUM_UIElemTypes__NewEnumerator125 = 120,
	BP_UIENUM_UIElemTypes__NewEnumerator126 = 121,
	BP_UIENUM_UIElemTypes__NewEnumerator127 = 122,
	BP_UIENUM_UIElemTypes__NewEnumerator128 = 123,
	BP_UIENUM_UIElemTypes__NewEnumerator129 = 124,
	BP_UIENUM_UIElemTypes__NewEnumerator130 = 125,
	BP_UIENUM_UIElemTypes__NewEnumerator131 = 126,
	BP_UIENUM_UIElemTypes__NewEnumerator132 = 127,
	BP_UIENUM_UIElemTypes__NewEnumerator133 = 128,
	BP_UIENUM_UIElemTypes__NewEnumerator134 = 129,
	BP_UIENUM_UIElemTypes__NewEnumerator135 = 130,
	BP_UIENUM_UIElemTypes__NewEnumerator138 = 131,
	BP_UIENUM_UIElemTypes__NewEnumerator139 = 132,
	BP_UIENUM_UIElemTypes__NewEnumerator140 = 133,
	BP_UIENUM_UIElemTypes__NewEnumerator141 = 134,
	BP_UIENUM_UIElemTypes__NewEnumerator142 = 135,
	BP_UIENUM_UIElemTypes__NewEnumerator143 = 136,
	BP_UIENUM_UIElemTypes__NewEnumerator144 = 137,
	BP_UIENUM_UIElemTypes__NewEnumerator145 = 138,
	BP_UIENUM_UIElemTypes__NewEnumerator146 = 139,
	BP_UIENUM_UIElemTypes__NewEnumerator147 = 140,
	BP_UIENUM_UIElemTypes__NewEnumerator148 = 141,
	BP_UIENUM_UIElemTypes__NewEnumerator149 = 142,
	BP_UIENUM_UIElemTypes__NewEnumerator150 = 143,
	BP_UIENUM_UIElemTypes__NewEnumerator152 = 144,
	BP_UIENUM_UIElemTypes__NewEnumerator153 = 145,
	BP_UIENUM_UIElemTypes__NewEnumerator154 = 146,
	BP_UIENUM_UIElemTypes__NewEnumerator155 = 147,
	BP_UIENUM_UIElemTypes__NewEnumerator156 = 148,
	BP_UIENUM_UIElemTypes__NewEnumerator157 = 149,
	BP_UIENUM_UIElemTypes__BP_UIENUM_MAX = 150
};



}

