#pragma once

// PlayerUnknown's Battle Ground Mobile (1.6.0) SDK

#include "PUBGM_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_classes.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.GetRotLoc
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_GetRotLoc_Params
{
	int                                                Index;                                                    // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
	struct FVector                                     Loc;                                                      // (Parm, OutParm, IsPlainOldData)
	struct FRotator                                    Rot;                                                      // (Parm, OutParm, IsPlainOldData)
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_9E6780B0492BFE9CFA8EBCABC42B1F15
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_9E6780B0492BFE9CFA8EBCABC42B1F15_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_0BA312A540B1A29D168E129F34DA8E70
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_0BA312A540B1A29D168E129F34DA8E70_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_D6D54F3140B4AF5BAA4A3EB5BDAE313A
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_D6D54F3140B4AF5BAA4A3EB5BDAE313A_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_2937D5A54DCE0E5F1DA0CAABB993A4D3
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_2937D5A54DCE0E5F1DA0CAABB993A4D3_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_E7639D1D44A0F344357A01A3129062DE
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_E7639D1D44A0F344357A01A3129062DE_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_A4DB934A474710A523DCCA9F881C740F
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_A4DB934A474710A523DCCA9F881C740F_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_9FD94D6A47D5A848CEE378A957666C16
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_9FD94D6A47D5A848CEE378A957666C16_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_BlendListByBool_EB1F08564A793033DD4696930DCA59C6
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_BlendListByBool_EB1F08564A793033DD4696930DCA59C6_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_AE3FFDC14029CA1B16D479A4BA2EFCB3
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_AE3FFDC14029CA1B16D479A4BA2EFCB3_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_132645434D89A88070EE61876032E912
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_132645434D89A88070EE61876032E912_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_A042FAA645A24C2EEE3594BB60429671
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_A042FAA645A24C2EEE3594BB60429671_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_915DA6024AEA86D2C1C7178A6CBA4E08
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_915DA6024AEA86D2C1C7178A6CBA4E08_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_5690AD374FFFC6F394277EA78CD83224
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_5690AD374FFFC6F394277EA78CD83224_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_62B3BAA045C80D302B4099974A3B052D
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_62B3BAA045C80D302B4099974A3B052D_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_4E41846F47D4D296B9CD1BBEBB45287F
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_4E41846F47D4D296B9CD1BBEBB45287F_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_5492275E4765921C13265FB393BE2A99
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_5492275E4765921C13265FB393BE2A99_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_38F4ADA2425644835E1C96A27D85F189
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_38F4ADA2425644835E1C96A27D85F189_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_EF54C8E741E711296FD7EAA35D4A04C4
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_AnimGraphNode_ModifyBone_EF54C8E741E711296FD7EAA35D4A04C4_Params
{
};

// Function SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint.SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C.ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint
struct USpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_C_ExecuteUbergraph_SpikeTrap_16Jnts_Spikes_mesh_Skeleton_AnimBlueprint_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

